SELECT
    c.CONVERSATION_ID AS conversation_id,
    u.USERNAME AS other_username,
    COALESCE(m.CONTENT, '') AS latest_message,
    COALESCE(m.TIMESTAMP, c.CREATED_AT) AS latest_time
FROM CONVERSATION_MEMBERS cm1
JOIN CONVERSATIONS c ON cm1.CONVERSATION_ID = c.CONVERSATION_ID
JOIN CONVERSATION_MEMBERS cm2 ON c.CONVERSATION_ID = cm2.CONVERSATION_ID AND cm2.USER_ID != cm1.USER_ID
JOIN USERS u ON cm2.USER_ID = u.USER_ID
LEFT JOIN (
    SELECT CONVERSATION_ID, CONTENT, TIMESTAMP
    FROM MESSAGE m1
    WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM MESSAGE m2
        WHERE m2.CONVERSATION_ID = m1.CONVERSATION_ID
    )
) m ON c.CONVERSATION_ID = m.CONVERSATION_ID
WHERE cm1.USER_ID = ?