USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
   	PASS_WORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    BIO NVARCHAR(1000),
    PICTURE_URL NVARCHAR(1000),
    BIRTH_DATE DATE NOT NULL,
    DATE_JOINED DATE NOT NULL DEFAULT (CURRENT_DATE),
    USER_TYPE ENUM('Student', 'Admin', 'Faculty', 'Alumni') NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    PRIVACY_LEVEL ENUM('Public', 'Private', 'FriendsOnly') NOT NULL,
    EMAIL_NOTIFICATIONS BOOLEAN NOT NULL,
    THEME ENUM('Light', 'Dark') NOT NULL,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ADMINS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUMNI (
    USER_ID INT UNSIGNED PRIMARY KEY,
    GRADUATION_YEAR INT,
    DEGREE_EARNED VARCHAR(100),
    CURRENT_EMPLOYER VARCHAR(100),
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BLOCKS (
    BLOCKER_ID INT UNSIGNED NOT NULL,
    BLOCKED_ID INT UNSIGNED NOT NULL,
    BLOCKED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BLOCKER_ID , BLOCKED_ID),
    FOREIGN KEY (BLOCKER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (BLOCKED_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    CHECK (BLOCKER_ID != BLOCKED_ID)
);



CREATE TABLE IF NOT EXISTS CONVERSATIONS (
    CONVERSATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_NAME VARCHAR(100),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONVERSATION_MEMBERS (
    CONVERSATION_ID INT UNSIGNED,
    USER_ID INT UNSIGNED,
    PRIMARY KEY (CONVERSATION_ID, USER_ID),
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS (CONVERSATION_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS HGroup (
    GroupID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CreatedByUserID INT UNSIGNED NOT NULL,
    GroupName VARCHAR(100) NOT NULL,
    StudyCategory VARCHAR(100) NOT NULL,
    Description TEXT,
    PrivacyType ENUM('Public', 'Private') NOT NULL DEFAULT 'Public',
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_hgroup
        PRIMARY KEY (GroupID),

    CONSTRAINT fk_hgroup_createdby
        FOREIGN KEY (CreatedByUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT uq_hgroup_name_category
        UNIQUE (GroupName, StudyCategory),

    CONSTRAINT chk_hgroup_name_not_blank
        CHECK (CHAR_LENGTH(TRIM(GroupName)) > 0),

    CONSTRAINT chk_hgroup_category_not_blank
        CHECK (CHAR_LENGTH(TRIM(StudyCategory)) > 0)
);

CREATE TABLE IF NOT EXISTS Event (
    EventID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CreatedByUserID INT UNSIGNED NOT NULL,
    GroupID INT UNSIGNED NULL,
    Title VARCHAR(150) NOT NULL,
    Description TEXT,
    Location VARCHAR(255) NOT NULL,
    StartDateTime DATETIME NOT NULL,
    EndDateTime DATETIME NOT NULL,
    PrivacyType ENUM('Public', 'Private') NOT NULL DEFAULT 'Public',
    EventStatus ENUM('Active', 'Past', 'Cancelled') NOT NULL DEFAULT 'Active',
    CancellationReason VARCHAR(255) NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_event
        PRIMARY KEY (EventID),

    CONSTRAINT fk_event_createdby
        FOREIGN KEY (CreatedByUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_event_group
        FOREIGN KEY (GroupID)
        REFERENCES HGroup(GroupID)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT chk_event_title_not_blank
        CHECK (CHAR_LENGTH(TRIM(Title)) > 0),

    CONSTRAINT chk_event_location_not_blank
        CHECK (CHAR_LENGTH(TRIM(Location)) > 0),

    CONSTRAINT chk_event_time_order
        CHECK (EndDateTime > StartDateTime),

    CONSTRAINT chk_event_cancel_reason_required
        CHECK (
            (EventStatus = 'Cancelled' AND CancellationReason IS NOT NULL AND CHAR_LENGTH(TRIM(CancellationReason)) > 0)
            OR
            (EventStatus <> 'Cancelled')
        )
);


CREATE TABLE IF NOT EXISTS EventRegistration (
    EventRegistrationID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EventID INT UNSIGNED NOT NULL,
    UserID INT UNSIGNED NOT NULL,
    RSVPStatus ENUM('Going', 'Not Going', 'Interested') NOT NULL,
    RegistrationStatus ENUM('Invited', 'Responded') NOT NULL DEFAULT 'Responded',
    RespondedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_eventregistration
        PRIMARY KEY (EventRegistrationID),

    CONSTRAINT fk_eventregistration_event
        FOREIGN KEY (EventID)
        REFERENCES Event(EventID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_eventregistration_user
        FOREIGN KEY (UserID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT uq_eventregistration_event_user
        UNIQUE (EventID, UserID)
);

CREATE TABLE IF NOT EXISTS FACULTY (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DEPARTMENT VARCHAR(100),
    OFFICE_LOCATION VARCHAR(150),
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS GroupMember (
    GroupMemberID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GroupID INT UNSIGNED NOT NULL,
    UserID INT UNSIGNED NOT NULL,
    RoleType ENUM('Owner','Moderator','Member','Mentor','Mentee') NOT NULL DEFAULT 'Member',
    MembershipStatus ENUM('Invited', 'Pending', 'Accepted', 'Declined', 'Left', 'Removed')
        NOT NULL DEFAULT 'Pending',
    JoinedAt TIMESTAMP NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_groupmember
        PRIMARY KEY (GroupMemberID),

    CONSTRAINT fk_groupmember_group
        FOREIGN KEY (GroupID)
        REFERENCES HGroup(GroupID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_groupmember_user
        FOREIGN KEY (UserID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT uq_groupmember_group_user
        UNIQUE (GroupID, UserID),

    CONSTRAINT chk_groupmember_joinedat_required_if_accepted
        CHECK (
            (MembershipStatus = 'Accepted' AND JoinedAt IS NOT NULL)
            OR
            (MembershipStatus <> 'Accepted')
        )
);


CREATE TABLE IF NOT EXISTS JobPosting (
    JobPostingID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PostedByUserID INT UNSIGNED NOT NULL,
    Title VARCHAR(150) NOT NULL,
    Company VARCHAR(150) NOT NULL,
    Location VARCHAR(150) NOT NULL,
    Description TEXT NOT NULL,
    ApplicationMethod ENUM('External Link', 'Email', 'Platform') NOT NULL,
    ApplicationURL VARCHAR(500) NULL,
    ContactEmail VARCHAR(255) NULL,
    Deadline DATETIME NOT NULL,
    JobStatus ENUM('Active', 'Closed', 'Expired') NOT NULL DEFAULT 'Active',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_jobposting
        PRIMARY KEY (JobPostingID),

    CONSTRAINT fk_jobposting_postedby
        FOREIGN KEY (PostedByUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_jobposting_title_not_blank
        CHECK (CHAR_LENGTH(TRIM(Title)) > 0),

    CONSTRAINT chk_jobposting_company_not_blank
        CHECK (CHAR_LENGTH(TRIM(Company)) > 0),

    CONSTRAINT chk_jobposting_location_not_blank
        CHECK (CHAR_LENGTH(TRIM(Location)) > 0),

    CONSTRAINT chk_jobposting_description_not_blank
        CHECK (CHAR_LENGTH(TRIM(Description)) > 0),

    CONSTRAINT chk_jobposting_method_requirements
        CHECK (
            (ApplicationMethod = 'External Link' AND ApplicationURL IS NOT NULL)
            OR
            (ApplicationMethod = 'Email' AND ContactEmail IS NOT NULL)
            OR
            (ApplicationMethod = 'Platform')
        )
);

CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    AUTHOR_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SHARED_POST_ID INT UNSIGNED DEFAULT NULL,
    GroupID INT UNSIGNED DEFAULT NULL,

    PRIMARY KEY (POST_ID),

    KEY FK_POST_AUTHOR (AUTHOR_ID),
    KEY fk_shared_post (SHARED_POST_ID),
    KEY fk_posts_group (GroupID),

    CONSTRAINT FK_POST_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_shared_post
        FOREIGN KEY (SHARED_POST_ID)
        REFERENCES POSTS(POST_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_posts_group
        FOREIGN KEY (GroupID)
        REFERENCES HGroup(GroupID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS LIKES (
  USER_ID INT UNSIGNED NOT NULL, 
  POST_ID INT UNSIGNED NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER_ID, POST_ID),

  CONSTRAINT FK_LIKE_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE, 

  CONSTRAINT FK_LIKE_POST
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS JobApplication (
    JobApplicationID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    JobPostingID INT UNSIGNED NOT NULL,
    ApplicantUserID INT UNSIGNED NOT NULL,
    ApplicationStatus ENUM('Submitted', 'Under Review', 'Accepted', 'Rejected', 'Declined', 'Withdrawn')
        NOT NULL DEFAULT 'Submitted',
    CoverLetter TEXT NULL,
    ResumeURL VARCHAR(500) NULL,
    AppliedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_jobapplication
        PRIMARY KEY (JobApplicationID),

    CONSTRAINT fk_jobapplication_jobposting
        FOREIGN KEY (JobPostingID)
        REFERENCES JobPosting(JobPostingID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_jobapplication_applicant
        FOREIGN KEY (ApplicantUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT uq_jobapplication_job_user
        UNIQUE (JobPostingID, ApplicantUserID)
);

CREATE TABLE IF NOT EXISTS MEDIA_ATTACHMENT (
    MEDIA_ID VARCHAR(255) PRIMARY KEY,
    URL VARCHAR(500) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    UPLOAD_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MESSAGE (
    MESSAGE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID INT UNSIGNED NOT NULL,
    SENDER_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS(CONVERSATION_ID),

    FOREIGN KEY (SENDER_ID) 
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
); 

-- NOTIFICATION table stores alerts for users when something happens
-- like a like, comment, share, or group-related action.
-- TriggerUserID is the user who caused the notification.
-- Author: Sophia Priola

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NotificationID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    RecipientUserID INT UNSIGNED NOT NULL,
    TriggerUserID INT UNSIGNED NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Message TEXT NOT NULL,
    IsRead BOOLEAN NOT NULL DEFAULT FALSE,
    RelatedPostID INT UNSIGNED DEFAULT NULL,
    RelatedGroupID INT UNSIGNED DEFAULT NULL,  
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notification
        PRIMARY KEY (NotificationID),

    CONSTRAINT fk_notification_recipient
        FOREIGN KEY (RecipientUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_notification_trigger
        FOREIGN KEY (TriggerUserID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_notification_post
        FOREIGN KEY (RelatedPostID)
        REFERENCES POSTS(POST_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_notification_group
        FOREIGN KEY (RelatedGroupID)
        REFERENCES HGroup(GroupID)
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS REPORT (
    REPORT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    REPORTER_ID INT UNSIGNED NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,

    CONSTRAINT FK_REPORT_REPORTER
        FOREIGN KEY (REPORTER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);

-- Creates table to store user session tokens
CREATE TABLE IF NOT EXISTS SESSIONS (
  TOKEN VARCHAR(128) PRIMARY KEY,
  USER_ID INT UNSIGNED NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    MAJOR VARCHAR(100),
    GRADUATION_YEAR INT,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    COMMENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT UNSIGNED NOT NULL,
    AUTHOR_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMENT_POST
        FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_COMMENT_AUTHOR
        FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

