USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
   	PASS_WORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    BIO NVARCHAR(1000),
    PICTURE_URL NVARCHAR(1000),
    BIRTH_DATE DATE NOT NULL,
    DATE_JOINED DATE NOT NULL DEFAULT (CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS ADMINS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUMNI (
    USER_ID INT UNSIGNED PRIMARY KEY,
    GRADUATION_YEAR INT,
    DEGREE_EARNED VARCHAR(100),
    CURRENT_EMPLOYER VARCHAR(100),
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BLOCKS (
    BLOCKER_ID INT UNSIGNED NOT NULL,
    BLOCKED_ID INT UNSIGNED NOT NULL,
    BLOCKED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BLOCKER_ID , BLOCKED_ID),
    FOREIGN KEY (BLOCKER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (BLOCKED_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    CHECK (BLOCKER_ID != BLOCKED_ID)
);

CREATE TABLE IF NOT EXISTS POSTS (
  POST_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
  AUTHOR_ID INT UNSIGNED NOT NULL, 
  CONTENT TEXT NOT NULL, 
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 

  CONSTRAINT FK_POST_AUTHOR
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT UNSIGNED NOT NULL,
    AUTHOR_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMENT_POST
        FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMMENT_AUTHOR
        FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS USER_GROUPS(
    GROUP_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    GROUP_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_BY INT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
    GROUP_ID INT UNSIGNED NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GROUP_ID, USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_EVENTS (
    EVENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    EVENT_DATE DATE NOT NULL,
    EVENT_TIME TIME NOT NULL,
    LOCATION VARCHAR(255),
    CREATED_BY INT UNSIGNED NOT NULL,
    GROUP_ID INT UNSIGNED,
    EVENT_TYPE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID)
);

CREATE TABLE IF NOT EXISTS EVENT_MEMBERS (
    EVENT_ID INT UNSIGNED NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    RSVP_STATUS VARCHAR(50),
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EVENT_ID, USER_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES USER_EVENTS(EVENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS FACULTY (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DEPARTMENT VARCHAR(100),
    OFFICE_LOCATION VARCHAR(150),
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIKES(
  USER_ID INT UNSIGNED NOT NULL, 
  POST_ID INT UNSIGNED NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER_ID, POST_ID),

  CONSTRAINT FK_LIKE_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE, 

  CONSTRAINT FK_LIKE_POST
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MEDIA_ATTACHMENT (
    MEDIA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(500) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    UPLOAD_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONVERSATIONS (
    CONVERSATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_NAME VARCHAR(100),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONVERSATION_MEMBERS (
    CONVERSATION_ID INT UNSIGNED,
    USER_ID INT UNSIGNED,
    PRIMARY KEY (CONVERSATION_ID, USER_ID),
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS (CONVERSATION_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MESSAGE (
    MESSAGE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID INT UNSIGNED NOT NULL,
    SENDER_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS(CONVERSATION_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) 
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_NOTIFICATION_RECIPIENT
        FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS REPORT (
    REPORT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    REPORTER_ID INT UNSIGNED NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,

    CONSTRAINT FK_REPORT_REPORTER
        FOREIGN KEY (REPORTER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSIONS (
  TOKEN VARCHAR(128) PRIMARY KEY,
  USER_ID INT UNSIGNED NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    MAJOR VARCHAR(100),
    GRADUATION_YEAR INT,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

