CREATE TABLE IF NOT EXISTS ALUMNI (
    USER_ID INT UNSIGNED PRIMARY KEY,
    GRADUATION_YEAR INT, 
    DEGREE_EARNED VARCHAR(100),
    CURRENT_EMPLOYER VARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
);