USE HUSKYHAPPENINGS; 

CREATE TABLE MEDIAATTACHMENT (
    MEDIAID VARCHAR(255) PRIMARY KEY,
    URL VARCHAR(500) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    UPLOADDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
