USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS MESSAGE (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    RECIPIENT_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_MESSAGE_SENDER
        FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_MESSAGE_RECIPIENT
        FOREIGN KEY (RECIPIENT_ID) REFERENCES USER(USER_ID)
        ON DELETE CASCADE
); 
