CREATE TABLE IF NOT EXISTS STUDENTS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    MAJOR VARCHAR(100),
    GRADUATION_YEAR INT, 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
);