CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
   	PASS_WORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    BIO NVARCHAR(1000),
    PICTURE_URL NVARCHAR(1000),
    BIRTH_DATE DATE NOT NULL,
    DATE_JOINED DATE NOT NULL DEFAULT CURRENT_DATE, 
);