CREATE TABLE IF NOT EXISTS BLOCKS (
    BLOCKER_ID INT UNSIGNED NOT NULL,
    BLOCKED_ID INT UNSIGNED NOT NULL,
    BLOCKED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BLOCKER_ID , BLOCKED_ID),
    FOREIGN KEY (BLOCKER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (BLOCKED_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE,
    CHECK (BLOCKER_ID != BLOCKED_ID)
);