USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS COMMENT (
    COMMENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    POST INT UNSIGNED NOT NULL,
    AUTHOR INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMENT_POST
        FOREIGN KEY (POST) REFERENCES POST(POST_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_COMMENT_AUTHOR
        FOREIGN KEY (AUTHOR) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
