CREATE TABLE IF NOT EXISTS CONVERSATIONS (
    CONVERSATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_NAME VARCHAR(100),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);