CREATE TABLE IF NOT EXISTS CONVERSATION_MEMBERS (
    CONVERSATION_ID INT UNSIGNED,
    USER_ID INT UNSIGNED,
    PRIMARY KEY (CONVERSATION_ID, USER_ID),
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS (CONVERSATION_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);