CREATE TABLE EVENT_MEMBERS (
    EVENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    RSVP_STATUS VARCHAR(50),
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EVENT_ID, USER_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
