CREATE TABLE IF NOT EXISTS FACULTY (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DEPARTMENT VARCHAR(100),
    OFFICE_LOCATION VARCHAR(150),
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);