CREATE TABLE GROUP_MEMBERS (
    GROUP_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GROUP_ID, USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
