USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS LIKES (
  USER INT UNSIGNED NOT NULL, 
  POST INT UNSIGNED NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER, POST),

  CONSTRAINT FK_LIKE_USER 
    FOREIGN KEY (USER) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE, 

  CONSTRAINT FK_LIKE_POST
    FOREIGN KEY (POST) REFERENCES POST(POST_ID)
    ON DELETE CASCADE, 
);
