USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS 'LIKE' (
  USER INT NOT NULL, 
  POST INT NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER, POST),

  CONSTRAINT FK_LIKE_USER 
    FOREIGN KEY (USER) REFERENCES USER(USER_ID)
    ON DELETE CASCADE, 

  CONSTRAINT FK_LIKE_POST
    FOREIGN KEY (POST) REFERENCES POST(POST_ID)
    ON DELETE CASCADE, 
);
