USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS LIKES (
  USER_ID INT UNSIGNED NOT NULL, 
  POST_ID INT UNSIGNED NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER_ID, POST_ID),

  CONSTRAINT FK_LIKE_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE, 

  CONSTRAINT FK_LIKE_POST
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
    ON DELETE CASCADE, 
);
