USE HUSKYHAPPENINGS; 

CREATE TABLE IF NOT EXISTS MEDIAATTACHMENT (
    MEDIA_ID VARCHAR(255) PRIMARY KEY,
    URL VARCHAR(500) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    UPLOAD_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
