USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS MESSAGE (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS(CONVERSATION_ID)
    MESSAGE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID INT UNSIGNED NOT NULL,
    RECIPIENT_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_MESSAGE_SENDER
        FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) 
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
); 
