USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS MESSAGE (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONVERSATION_ID)
        REFERENCES CONVERSATIONS(CONVERSATION_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) 
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
); 
