USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT_ID INT UNSIGNED NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_NOTIFICATION_RECIPIENT
        FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);
