USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS POST (
  POST_ID INT AUTO_INCREMENT PRIMARY KEY, 
  AUTHOR_ID INT NOT NULL, 
  CONTENT TEXT NOT NULL, 
  TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 

  CONSTRAINT FK_POST_AUTHOR
    FOREIGN KEY (AUTHOR_USER_ID) REFERENCES USER(USER_ID)
    ON DELETE CASCADE
);
