USE HUSKYHAPPENINGS;

CREATE TABLE IF NOT EXISTS REPORT (
    REPORT_ID INT AUTO_INCREMENT PRIMARY KEY,
    REPORTER_ID INT NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,

    CONSTRAINT FK_REPORT_REPORTER
        FOREIGN KEY (REPORTER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);
