-- Creates table to store user session tokens
CREATE TABLE IF NOT EXISTS SESSIONS (
  TOKEN VARCHAR(128) PRIMARY KEY,
  USER_ID INT UNSIGNED NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
);