CREATE TABLE IF NOT EXISTS USER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    PRIVACY_LEVEL ENUM('Public', 'Private', 'FriendsOnly') NOT NULL,
    EMAIL_NOTIFICATIONS BOOLEAN NOT NULL,
    THEME ENUM('Light', 'Dark') NOT NULL,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);